// Install VS-Code extension "REST Client" to run this file
// Backend Server runs here, and fetches from MongoDB.

// To start the test server, run: npm run devtest

###
// Get all Blogs
GET http://localhost:3003/api/blogs

###
// Create a new Blog
POST http://localhost:3003/api/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImdyZXkiLCJpZCI6IjY2OWRmODIwN2YyZTkyZGI4ZjRmYmE2ZCIsImlhdCI6MTcyMTYyODcxOSwiZXhwIjoxNzIxNjM1OTE5fQ.GRkzY0-hCSBuGe1wKU_kgR8g9Wg2STBOzgvP8mnY_WU
content-type: application/json

{
        "title": "Grey's pants",
        "url": "https://gerteck.github.io",
        "likes": 2
}

### 
// Users
GET http://localhost:3003/api/users

###
POST http://localhost:3003/api/users
content-type: application/json

{
        "username": "gerteckRequest",
        "name": "Ger Teck",
        "password": "password"
}

###
POST http://localhost:3003/api/users
content-type: application/json

{
        "username": "grey",
        "name": "sir-grey",
        "password": "password"
}


### 
// For Login
POST http://localhost:3003/api/login
content-type: application/json

{
        "username": "grey",
        "password": "password"
}


