// Install VS-Code extension "REST Client" to run this file
// Backend Server runs here, and fetches from MongoDB.

// To start the test server, run: npm run devtest

###
// Get all Blogs
GET http://localhost:3003/api/blogs

###
// Create a new Blog
POST http://localhost:3003/api/blogs
content-type: application/json

{
        "title": "New Test Blog 2",
        "author": "Ger Teck",
        "url": "https://gerteck.github.io",
        "likes": 999
}

### 
// Users
GET http://localhost:3003/api/users

###
POST http://localhost:3003/api/users
content-type: application/json

{
        "username": "gerteckRequest",
        "name": "Ger Teck",
        "password": "password"
}


